name: Django CI

on:
  push:
    branches: [ develop ]
    paths-ignore: 'frontend/angularapp/**'
  pull_request:
    branches: [ develop ]
    paths-ignore: 'frontend/angularapp/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      uses: dschep/install-pipenv-action@v1
      run: |
        pipenv install
    - name: Run Tests
      run: |
        pipenv run test
