name: Pylint

on:
  push:
    branches: [ '**' ]
    paths-ignore: 'frontend/angularapp/**'
  pull_request:
    branches: [ develop ]
    paths-ignore: 'frontend/angularapp/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      uses: dschep/install-pipenv-action@v1
      run: |
        pipenv install --dev
    - name: Analysing the code with pylint
      env:
        DJANGO_SETTINGS_MODULE: balneario.settings
      run: |
        pipenv run lint
